  - name: install java
    apt: name=default-jdk state=present
  - name: add tomcat group
    group: name=tomcat state=present
  - name: add tomcat user
    user:
     name: tomcat
     shell: /bin/false
     group: tomcat
     home: /opt/tomcat
  - name: unarchieve the file
    unarchive:
     src: "{{tomcat_url}}"
     dest: "{{dest_path}}"
     remote_src: yes
     extra_opts: "--strip-components=1"
  - name: change the group ownership
    file:
     path: /opt/tomcat
     group: tomcat
     owner: tomcat
     recurse: yes
  - name: copy the tomcat service file
    template:
     src: templates/tomcat.service.j2
     dest: /etc/systemd/system/tomcat.service 
    notify:
      - start tomcat
